import { Player1 } from "../Entity/Player1";
import Wall from "../Entity/Wall";
import { Level } from "./Level";

export class Level1 extends Level {
  constructor() {
    const structure = [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        [new Wall()],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [new Wall()],
        null,
        null,
      ],
      [
        null,
        null,
        [new Wall()],
        null,
        null,
        [new Wall()],
        [new Wall()],
        [new Wall()],
        [new Wall()],
        [new Wall()],
        null,
        null,
        [new Wall()],
        null,
        null,
      ],
      [
        null,
        null,
        [new Wall()],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [new Wall()],
        null,
        null,
      ],
      [
        null,
        null,
        [new Wall()],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [new Wall()],
        null,
        null,
      ],
      [
        null,
        null,
        [new Wall()],
        null,
        null,
        [new Wall()],
        [new Wall()],
        [new Wall()],
        [new Wall()],
        [new Wall()],
        null,
        null,
        [new Wall()],
        null,
        null,
      ],
      [
        null,
        null,
        [new Wall()],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [new Wall()],
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [new Player1()],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ];

    super(structure);
  }
}
