import { Level } from "./Level";

export class Level1 extends Level {
  constructor() {
    const structure = [
      [
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
      ],
      [
        [{ type: "wall" }],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [{ type: "wall" }],
      ],
      [
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
      ],
      [
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
      ],
      [
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
      ],
      [
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
      ],
      [
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
      ],
      [
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [{ type: "wall" }],
        null,
        null,
        [{ type: "wall" }],
      ],
      [
        [{ type: "wall" }],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [{ type: "player" }],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        [{ type: "wall" }],
      ],
      [
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
        [{ type: "wall" }],
      ],
    ];

    super(structure);
  }
}
